<?xml version="1.0"?>
<wsdl:definitions name="ContractFirst"
                  targetNamespace="http://example.com/contractfirst"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:ns1="http://example.com/contractfirst"
                  xmlns:tns="http://example.com/contractfirst"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <wsdl:types>
        <xs:schema>

            <xs:import namespace="http://example.com/contractfirst"
                       schemaLocation="../xsd/sum.xsd"/>
        </xs:schema>

    </wsdl:types>

    <wsdl:message name="sumSalary">
        <wsdl:part element="ns1:sumSalary" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="sumSalaryResponse">
        <wsdl:part element="ns1:sumSalaryResponse" name="parameters"/>
    </wsdl:message>

    <wsdl:portType name="ContractFirst">
        <wsdl:operation name="sumSalary">
            <wsdl:input message="ns1:sumSalary" name="sumSalary"/>
            <wsdl:output message="ns1:sumSalaryResponse" name="sumSalaryResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="ContractFirst_SoapBinding" type="ns1:ContractFirst">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="sumSalary">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="sumSalary">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="sumSalaryResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="ContractFirst_Service">
        <wsdl:port binding="tns:ContractFirst_SoapBinding" name="ContractFirst_Port">
            <soap:address location="http://localhost:8080/cxf/test2"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>